package rml2shex.util;

public class Symbols {
    public static final String A = "a";
    public static final String AMPERSAND = "&";
    public static final String AND = "AND";
    public static final String ASTERISK = "*";
    public static final String AT = "@";
    public static final String BACKSLASH = "\\";
    public static final String BASE = "BASE";
    public static final String BNODE = "BNODE";
    public static final String CARET = "^";
    public static final String CLOSE_BRACE = "}";
    public static final String CLOSE_BRACKET = "]";
    public static final String CLOSED = "CLOSED";
    public static final String CLOSE_PARENTHESIS = ")";
    public static final String COLON = ":";
    public static final String COMMA = ",";
    public static final String DASH = "-";
    public static final String DOLLAR = "$";
    public static final String DOT = ".";
    public static final String DOUBLE_QUOTATION_MARK = "\"";
    public static final String EMPTY = "";
    public static final String EQUAL = "=";
    public static final String GRAVE_ACCENT = "`";
    public static final String GT = ">";
    public static final String HASH = "#";
    public static final String IMPORTS = "IMPORTS";
    public static final String IRI = "IRI";
    public static final String LT = "<";
    public static final String NEWLINE = "\n";
    public static final String OPEN_BRACE = "{";
    public static final String OPEN_BRACKET = "[";
    public static final String OPEN_PARENTHESIS = "(";
    public static final String OR = "OR";
    public static final String PIPE = "|";
    public static final String PLUS = "+";
    public static final String PREFIX = "PREFIX";
    public static final String QUESTION_MARK = "?";
    public static final String REF = "ref";
    public static final String SEMICOLON = ";";
    public static final String SINGLE_QUOTATION_MARK = "'";
    public static final String SLASH = "/";
    public static final String SPACE = " ";
    public static final String TAB = "    ";
    public static final String UNDERSCORE = "_";
    public static final String ZERO = "0";
    public static final String base = "base";
    public static final String prefix = "prefix";
}
